config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  resources :markdown_inputs, path: 'gfm'

  resources :pages, only: %i[show]
  resources :regexes, only: %i[show]
  resources :regex_sessions, only: %i[index show create update destroy], path: 'r'
  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#index"
end

app/views/pages/highlight.html.erb
<!-- test integrating of highlight.js with a few different source examples -->

<% content_for(:title) { "syntax highlighting" } %>

<%= render "layouts/nav" %>

<article class="examples" data-controller="highlight-sources">
  <h1>Testing Syntax Highlighting</h1>

  <p>Here's some ruby.</p>

  <pre class="language-ruby">require_relative "boot"

require "rails/all"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Exalog
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 8.0

    # Please, add to the `ignore` list any other `lib` subdirectories that do
    # not contain `.rb` files, or that should not be reloaded or eager loaded.
    # Common ones are `templates`, `generators`, or `middleware`, for example.
    config.autoload_lib(ignore: %w[assets tasks])

    # Configuration for the application, engines, and railties goes here.
    #
    # These settings can be overridden in specific environments using the files
    # in config/environments, which are processed later.
    #
    # config.time_zone = "Central Time (US & Canada)"
    # config.eager_load_paths << Rails.root.join("extras")
  end
end
</pre>

  <p>Here's some javascript</p>

  <pre class="language-javascript">import { Controller } from "@hotwired/stimulus"
import hljs from 'highlight.js';

export default class extends Controller {
  connect() {
    this.element.querySelectorAll("code, pre").forEach((el) => {
      const lang = el.getAttribute("language")
      console.log(lang, el)
      if (lang) {
        hljs.highlightElement(el, { language: lang });
      }
    });
  }
}
</pre>

  <p>And, for now, we'll just add in a little SQL</p>

  <pre class="language-sql">SELECT * FROM users
  WHERE id IN (SELECT user_id FROM admin_users);</pre>

  <p>And here is a sentence with an inline code example: <code class="language-ruby">puts 'Hello world!'</code>.</p>
</article>

app/views/pages/index.html.erb
<% content_for(:title) { "exalog - Carl's blog/toybox" } %>

<%= render "layouts/nav" %>

<ul class="page-list">
  <li>
    <%= link_to regex_path("cheats") do %>
      <em>Ruby Regex Cheat Sheet</em>
      <small>Regular expression reference for any Perl Compatible Regular Expressions (PCRE) system, but particularly ruby.</small>
    <% end %>
  </li>
  <li>
    <%= link_to page_path("pixels") do %>
      <em>Dead Pixel Finder</em>
      <small>Simple tool that toggles between white/black, and primary colors (on click) to help you find any stuck or dead pixels on an LCD/OLED.</small>
    <% end %>
  </li>
  <li>
    <%= link_to new_markdown_input_path do %>
      <em>Markdown Preview</em>
      <small>Paste in some markdown (with optional github flavor) and get a rendered HTML output.</small>
    <% end %>
  </li>
  <li>
    <%= link_to regex_sessions_path do %>
      <em>Regular Expression Playground</em>
      <small>Edit and test our complex regular expressions in real-time.</small>
    <% end %>
  </li>
<ul>

app/views/pages/pixels.html.erb
<% content_for(:title) { "Dead Pixel Finder" } %>
<% content_for(:head) do %>
  <style>
    body.pixels {
      height: 100vh;
      background: #000;
    }
  </style>
<% end %>
<% add_body_controller(:pixels) %>
<% add_body_class(:pixels) %>